# requires: xhtml2pdf>=0.2.11
"""pdf_export.py — Convert markdown to a styled PDF (bytes) for Streamlit download."""

from __future__ import annotations

import io
import logging

import markdown

logger = logging.getLogger(__name__)

_CSS = """
body { font-family: Arial, sans-serif; font-size: 11pt; color: #222; margin: 2cm; }
h1 { color: #00b4d8; font-size: 18pt; border-bottom: 2px solid #00b4d8; padding-bottom: 4px; }
h2 { color: #0077a8; font-size: 14pt; margin-top: 16pt; }
h3 { color: #333; font-size: 12pt; }
table { width: 100%; border-collapse: collapse; margin: 8pt 0; font-size: 10pt; }
th { background: #00b4d8; color: white; padding: 4pt 6pt; text-align: left; }
td { border: 1px solid #ddd; padding: 4pt 6pt; }
tr:nth-child(even) { background: #f5f5f5; }
code { background: #f0f0f0; padding: 1pt 3pt; border-radius: 2pt; font-size: 10pt; }
pre { background: #f0f0f0; padding: 8pt; border-radius: 4pt; font-size: 9pt; }
blockquote { border-left: 3px solid #00b4d8; margin-left: 0; padding-left: 10pt; color: #555; }
@page { margin: 2cm; @bottom-right { content: "Generated by QAI Consultant"; font-size: 8pt; color: #aaa; } }
"""


def markdown_to_pdf(md_text: str, title: str = "QAI Consultant Report") -> bytes | None:
    """Convert a markdown string to a styled PDF and return the raw bytes.

    Parameters
    ----------
    md_text:
        The markdown source text to render.
    title:
        Document title injected as an <h1> at the top of the PDF.

    Returns
    -------
    bytes | None
        PDF bytes on success, ``None`` on any error (silent fail so callers
        can skip the download button rather than crashing).
    """
    try:
        from xhtml2pdf import pisa  # noqa: PLC0415 — deferred to avoid hard import at startup
    except ImportError:
        logger.warning("xhtml2pdf is not installed; PDF export is unavailable.")
        return None

    try:
        body_html = markdown.markdown(
            md_text,
            extensions=["tables", "fenced_code", "nl2br"],
        )

        html = (
            f'<!DOCTYPE html>\n'
            f'<html>\n'
            f'<head>\n'
            f'  <meta charset="UTF-8" />\n'
            f'  <title>{title}</title>\n'
            f'  <style>{_CSS}</style>\n'
            f'</head>\n'
            f'<body>\n'
            f'  <h1>{title}</h1>\n'
            f'  {body_html}\n'
            f'</body>\n'
            f'</html>\n'
        )

        output = io.BytesIO()
        result = pisa.CreatePDF(html, dest=output, encoding="UTF-8")

        if result.err:
            logger.warning("xhtml2pdf reported %d error(s) during PDF generation.", result.err)
            return None

        return output.getvalue()

    except Exception:
        logger.exception("Unexpected error during PDF generation.")
        return None
